<a href="https://colab.research.google.com/github/chetx27/sic/blob/main/day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# day 5
import numpy as np

data = np.random.randn(2, 3)
data

array([[ 0.45585089,  0.39026061,  1.0728256 ],
       [ 0.40676495, -1.550056  ,  0.72295885]])

In [6]:
np.mean(data)

np.float64(0.2497674828898279)

In [5]:
data2=np.random.randn(100,100)
data2

array([[-0.99378273, -1.25802619,  0.30467019, ...,  0.31879136,
        -0.41794113,  0.98578268],
       [-0.40017998,  0.53118548,  0.29977998, ...,  0.97546698,
         0.89065126,  2.95001866],
       [-0.29228725, -1.5673839 , -1.83036609, ...,  0.99327984,
        -0.54401354,  0.41921379],
       ...,
       [ 0.18754066,  0.2796692 , -0.04902728, ...,  0.04357672,
         0.14725228,  0.49298409],
       [ 1.02113581,  0.54137814,  1.24005988, ...,  1.70479094,
        -0.62412443, -0.82418245],
       [-1.17727642, -0.05939357,  1.25299392, ...,  0.99203863,
        -0.02876788, -0.98367369]])

In [8]:
# pthin list vs numpy array
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [11]:
list(range(100))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [13]:
type(np.arange(1000))

numpy.ndarray

In [15]:
%time for i in range(1000): np.arange(10000000)*2

CPU times: user 21.2 s, sys: 23.3 s, total: 44.5 s
Wall time: 47.3 s


In [16]:
%time for i in range(1000):list(range(1000000))*2

CPU times: user 40.8 s, sys: 14.9 s, total: 55.7 s
Wall time: 56 s


In [ ]:
# alter the array weve created
# append joins 2 lists

In [18]:
a=np.array([1,2,3])
b=np.append(a,[4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [20]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [22]:
y = np.append(x, [[9, 9]], axis=0)  # elements added vertically to 2D array x
y

array([[1, 2],
       [3, 4],
       [9, 9]])

In [24]:
z = np.append(x, [[9], [9]], axis=1)
z

array([[1, 2, 9],
       [3, 4, 9]])

In [ ]:
# delete the arrays for 2d array

In [25]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.delete(a,0)

array([2, 3, 4, 5, 6])

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# numpy in operations on array

In [28]:
np.delete(a,0,axis=0)

array([[4, 5, 6]])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.delete(a,1,axis=1)

array([[1, 3],
       [4, 6]])

In [ ]:
# numpy array basic operations

In [31]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [32]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
ar1+ar2

array([5, 7, 9])

In [33]:
ar1*ar2

array([ 4, 10, 18])

In [34]:
ar1-ar2

array([-3, -3, -3])

In [35]:
ar1/ar2

array([0.25, 0.4 , 0.5 ])

In [38]:
print(ar1, ar1.shape)
print(ar2, ar2.shape)

[1 2 3] (3,)
[4 5 6] (3,)


In [40]:
a=[3,4,6]
10*a

[3,
 4,
 6,
 3,
 4,
 6,
 3,
 4,
 6,
 3,
 4,
 6,
 3,
 4,
 6,
 3,
 4,
 6,
 3,
 4,
 6,
 3,
 4,
 6,
 3,
 4,
 6,
 3,
 4,
 6]

In [41]:
a


[3, 4, 6]

In [42]:
np.repeat(b,3)

array([4, 4, 4, 5, 5, 5, 6, 6, 6])

In [43]:
np.tile(b,3)

array([4, 5, 6, 4, 5, 6, 4, 5, 6])

In [47]:
c=np.arange(9)
c=c.reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
c.shape

(3, 3)

In [50]:
np.tile(c, 3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [51]:
ar2

array([4, 5, 6])

In [52]:
ar2**2

array([16, 25, 36])

In [53]:
ar1/(ar2**2)

array([0.0625    , 0.08      , 0.08333333])

In [54]:
ar3=np.array([10,20,30])
ar3

array([10, 20, 30])

In [55]:
ar3>10

array([False,  True,  True])

In [56]:
x=np.array([0,1,2,3])
x**3

array([ 0,  1,  8, 27])

In [57]:
np.sqrt(x)
# universal

array([0.        , 1.        , 1.41421356, 1.73205081])

In [59]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
x=np.arange(1,11)
x.sum()

np.int64(55)

In [62]:
x_mean=x.mean()
x_mean

np.float64(5.5)

In [63]:
x-x_mean

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [64]:
(x-x_mean)**2

array([20.25, 12.25,  6.25,  2.25,  0.25,  0.25,  2.25,  6.25, 12.25,
       20.25])

In [67]:
dev=(x-x_mean)**2
dev.sum()

np.float64(82.5)

In [68]:
dev.sum()/x.size

np.float64(8.25)

In [69]:
x.var()

np.float64(8.25)

In [70]:
np.sqrt(x.var())

np.float64(2.8722813232690143)

In [71]:
x.std()

np.float64(2.8722813232690143)

In [72]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])