<a href="https://colab.research.google.com/github/chetx27/sic/blob/main/sic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.array([1,3,5,7,9])
type(arr)

numpy.ndarray

In [ ]:
id(arr)

134251163695312

In [ ]:
arr1= np.array([133,3,524,643,2])
id(arr1)

134251163696944

In [ ]:
# 2*2 matrix
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
display(arr2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 5*5
arr5d = np.array([[1, 2, 3,5,7], [4, 5, 6,4,8], [7, 8, 9,9,3],[3,6,7,2,1],[2,6,9,2,1]])
display(arr5d)

array([[1, 2, 3, 5, 7],
       [4, 5, 6, 4, 8],
       [7, 8, 9, 9, 3],
       [3, 6, 7, 2, 1],
       [2, 6, 9, 2, 1]])

In [ ]:
# Creation of rand elements in an matrix
arr5 = np.random.rand(10, 11)
display(arr5)

array([[0.32810289, 0.69884319, 0.96372819, 0.44116463, 0.20956693,
        0.82066213, 0.86617679, 0.32297479, 0.05807188, 0.87724315,
        0.36409924],
       [0.37958052, 0.25838583, 0.31535315, 0.78673229, 0.95642829,
        0.48623614, 0.29033584, 0.50517552, 0.71032157, 0.82167378,
        0.06539138],
       [0.99393134, 0.12494217, 0.33768084, 0.86053651, 0.9840336 ,
        0.44946286, 0.68222562, 0.93612788, 0.79857054, 0.93873454,
        0.13290066],
       [0.88769276, 0.38553854, 0.72061902, 0.6223845 , 0.42722808,
        0.92956223, 0.72050002, 0.60083496, 0.01582213, 0.37966401,
        0.43409655],
       [0.85775498, 0.93274664, 0.21844217, 0.97647624, 0.98063414,
        0.32190529, 0.71114841, 0.28552809, 0.03070879, 0.04142567,
        0.90545618],
       [0.22356601, 0.77235294, 0.71611839, 0.61092789, 0.46606838,
        0.20636705, 0.99597297, 0.08086289, 0.7927752 , 0.63809547,
        0.62162254],
       [0.65287961, 0.64688311, 0.6635128 , 0.2265045 , 0.

In [ ]:
# completely fill with zero

random = np.zeros((10, 10))
display(random)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# completely fill with numbers between 1 to 5

matrix = np.random.randint(1, 6, size=(10, 10))
display(matrix)

array([[3, 3, 3, 3, 3, 1, 4, 5, 3, 5],
       [1, 5, 1, 5, 5, 4, 2, 4, 5, 3],
       [1, 1, 5, 2, 5, 3, 4, 1, 3, 4],
       [4, 3, 3, 1, 4, 5, 2, 4, 4, 5],
       [4, 1, 5, 1, 4, 4, 1, 2, 3, 3],
       [2, 3, 1, 5, 4, 5, 4, 3, 4, 4],
       [5, 1, 1, 1, 1, 2, 2, 1, 2, 2],
       [3, 5, 1, 1, 3, 3, 3, 4, 1, 1],
       [4, 2, 4, 2, 3, 5, 4, 1, 5, 5],
       [4, 2, 5, 3, 5, 4, 4, 2, 3, 3]])

In [ ]:
# completely fill with numbers with one number

np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
arr3=np.array([2,3,3,4,4,4])
np.copy(arr3)


array([2, 3, 3, 4, 4, 4])

In [ ]:
id(arr5)

134251164042128

In [ ]:
id(arr3)

134251162244976

In [ ]:
tuple= (1,2,3,4,'nice',5.0)
type(tuple)

tuple