<a href="https://colab.research.google.com/github/chetx27/sic/blob/main/sicday3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
import numpy as np
[i for i in np.arange(10)]

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
len10=np.arange(10)

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
len(len10)

10

In [ ]:
len10.size

10

In [ ]:
np.array([111,2.3,True])

array([111. ,   2.3,   1. ])

In [ ]:
arr5=np.array([111,2,3,True])

In [ ]:
arr5[0]

np.int64(111)

In [ ]:
arr5[0]

np.int64(111)

In [ ]:
type(arr5[0])

numpy.int64

In [ ]:
arr7 = np.array(['apple','banana','strawberry'])
type(arr7[0])

numpy.str_

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.linspace(10,10,20)

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10.])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
l1[0][0]

1

In [ ]:
arr2d = np.array(l1)
arr2d.ndim

2

In [ ]:
arr1d=np.array([1,3,5,7,9])
arr1d.ndim

1

In [39]:
np.array([[2,3,4],[3,5,7], [3,6,8],[4,9,0]])

array([[2, 3, 4],
       [3, 5, 7],
       [3, 6, 8],
       [4, 9, 0]])

In [41]:
arr3d = np.array([[[1,3],[9,7]],[[5,8],[9,0]]])
arr3d.ndim

3

In [42]:
arr3d[0][0][0]

np.int64(1)

In [44]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
arr2d=np.zeros((2,3),dtype='int64')
arr2d

array([[0, 0, 0],
       [0, 0, 0]])

In [50]:
type(arr2d[0][0])

numpy.int64

In [51]:
arr2d.astype('float32')

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [53]:
arr2d2 = arr2d.astype('float32')
arr2d2

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [54]:
#properties of numpy array

a=np.array([[1,2,4],[5,6,8]])

In [55]:
a.size

6

In [56]:
a.shape

(2, 3)

In [57]:
a.ndim

2

In [59]:
# 1 d array shape
b=np.array([1,2,4,5,7,7])
b.shape


(6,)

In [60]:
a2=np.arange(15)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
a2.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])